import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'
import path from 'path'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    pool: 'threads',
    maxWorkers: 1,
    setupFiles: ['./src/tests/setup.js'],
    include: ['src/**/*.{test,spec}.js'],
    clearMocks: true,
    restoreMocks: true,
    coverage: {
      provider: 'v8',
      reportsDirectory: './coverage',
      reporter: ['text', 'html', 'lcov'],
      include: ['src/**/*.{js,vue}'],
      exclude: [
        'src/**/*.spec.js',
        'src/**/*.test.js',
        'src/tests/**',
        'src/main.js',
        'src/plugins/**',
        'src/assets/**',
      ],
      thresholds: {
        'src/shared/auth/api/jwt.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/shared/auth/api/token.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/utils/error.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/shared/auth/store/authJWT.module.js': {
          lines: 80,
          functions: 60,
          branches: 80,
          statements: 80,
        },
        'src/shared/auth/store/authToken.module.js': {
          lines: 80,
          functions: 75,
          branches: 75,
          statements: 80,
        },
        'src/store/modules/alert.module.js': {
          lines: 85,
          functions: 80,
          branches: 100,
          statements: 85,
        },
        'src/composables/useVuelidateErrorMessages.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/shared/router/guards.js': {
          lines: 85,
          functions: 85,
          branches: 80,
          statements: 85,
        },
        'src/shared/router/legacy-guard-compat.js': {
          lines: 85,
          functions: 85,
          branches: 80,
          statements: 85,
        },
        'src/http/axiosInterceptors.js': {
          lines: 85,
          functions: 85,
          branches: 80,
          statements: 85,
        },
        'src/apps/taberna/cart/api/cart.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/cart/store/cart.module.js': {
          lines: 80,
          functions: 75,
          branches: 75,
          statements: 80,
        },
        'src/apps/taberna/orders/api/orders.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/orders/store/orderActions.js': {
          lines: 90,
          functions: 90,
          branches: 85,
          statements: 90,
        },
        'src/apps/taberna/orders/store/orders.module.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/product/api/products.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/product/api/categories.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/product/store/product.module.js': {
          lines: 80,
          functions: 75,
          branches: 75,
          statements: 80,
        },
        'src/apps/taberna/profiles/api/orders.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/taberna/profiles/store/profiles.module.js': {
          lines: 80,
          functions: 75,
          branches: 75,
          statements: 80,
        },
        'src/apps/social/posts/api/feed.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/posts/api/actions.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/posts/api/posts.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/posts/api/search.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/posts/api/trends.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/posts/store/posts.module.js': {
          lines: 65,
          functions: 50,
          branches: 50,
          statements: 65,
        },
        'src/apps/social/profiles/api/profile.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/profiles/api/friendship.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/profiles/store/profiles.module.js': {
          lines: 45,
          functions: 40,
          branches: 35,
          statements: 45,
        },
        'src/apps/social/chat/api/chat.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/chat/store/chat.module.js': {
          lines: 85,
          functions: 85,
          branches: 75,
          statements: 85,
        },
        'src/apps/social/notifications/api/notifications.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/social/notifications/store/notifications.module.js': {
          lines: 85,
          functions: 85,
          branches: 75,
          statements: 85,
        },
        'src/apps/ai_lab/api/chat.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/ai_lab/api/image.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/ai_lab/api/voice.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/ai_lab/api/realtime.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
        'src/apps/ai_lab/store/aiLab.module.js': {
          lines: 70,
          functions: 65,
          branches: 60,
          statements: 70,
        },
        'src/apps/apps_manager/api/vueApps.js': {
          lines: 90,
          functions: 90,
          branches: 90,
          statements: 90,
        },
      },
    },
  },
})
